# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Think with data science
tagline:             'Louis Willems'
description:         'Louis Willems" target="_blank">@mdo</a>.'
url:                 https://louiswillems.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Louis Wilems
  email:             louis.willems@outlook.com

# Custom vars
version:             1.0.0
